### ISSUE TITLE
2 chars and more string length delimiter prevents from deleting (with backspace)

### ISSUE THREAD

**Issue by dimagimburg** [nosir/cleave.js#178]
reproduce:
* options: `creditCard: true`, `delimiter: "--"` (-- originally for me was two spaces but)
* type 1234 5678 (which turns into `1234--56789`)
* backspace until you get stuck on the `1234--` and cannot delete any more

**Comment by nosir** [comment]
Fixed and released in v0.7.21
However, multiple length delimiter is just an experiment feature though.

**Comment by adoxus** [comment]
Same issue is still reproducible while using multiple delimiters, such as, `delimiters: [') ']` or `delimiters: [' (', ') ']`for a use case of phone numbers.
