### ISSUE TITLE
noImmediatePrefix blocks input changes

### ISSUE THREAD

**Issue by yardz** [nosir/cleave.js#455]
To reproduce the error or describe your requirement with a jsfiddle url would be appreciated:
- Fork this with React JS component: https://jsfiddle.net/nosir/gLLsrxxf/
- [error example](https://jsfiddle.net/yardz/yvsgmohn/43/)

## noImmediatePrefix 
When ``noImmediatePrefix: true`` the inputs do not update the values.

**Comment by kshnurov** [comment]
It was broken by this commit: https://github.com/nosir/cleave.js/commit/cf53ffb3c1505ebe0a415c792392defb1d87434f#diff-74644b0cb7bbf916c2165dad9afab007R1298

**Comment by dev-itbinc** [comment]
Any updates on it?

**Comment by kshnurov** [comment]
@nosir could you please look into this?

**Comment by franks921** [comment]
I think this issues extends beyond cleave-react as this is causing the same issues for me using the following manual phone number format

```js
new Cleave(this.element, {
  numericOnly:       true,
  prefix:            this.countryCode,
  noImmediatePrefix: true,
  blocks:            [0, this.countryCode.length, 0, 3, 0, 3, 4],
  delimiters:        ['+', ' ', '(', ')', ' ', '-']
})
```

Everything works fine until we add prefixing. I ended up rolling back to `v.1.4.7` as a temporary solution

**Comment by vrepsys** [comment]
Same problem here.

**Comment by nosir** [comment]
Fix released in v1.5.3, npm published.
Thanks

**Comment by kshnurov** [comment]
@nosir this is not completely fixed, input with prefix won't clear.
To reproduce:
- create an input with prefix, fill it
- select all (Ctrl+A/Cmd+A)
- clear (Backspace)
- input value stays the same

Selecting everything but prefix will clear the field.
